### ISSUE TITLE
Error on unchanged, clean install

### ISSUE THREAD

**Issue by hirasso** [yoren/angularjs-demo-theme#1]
Hi there, thank you for your effort! I just tried to install your theme, but I get the following error in the js console: 

``` javascript
TypeError: Cannot read property 'replace' of undefined
    at Gb (angular.min.js:93)
    at Me.$get (angular.min.js:100)
    at Object.e [as invoke] (angular.min.js:36)
    at angular.min.js:38
    at d (angular.min.js:36)
    at Object.e [as invoke] (angular.min.js:36)
    at angular.min.js:38
    at d (angular.min.js:36)
    at Object.e [as invoke] (angular.min.js:36)
    at angular.min.js:47
```

**Comment by yoren** [comment]
@rassoh Thanks for your feedback. This error comes from the `<base href="/jsonapi/">` setting in the document head. I've been asked plenty of times in the comments of [my tutorial](https://1fix.io/blog/2014/11/05/angularjs-json-api-wp-theme/).

I decided to change it to a dynamic string now it will get the root directory automatically. If you're interested in this topic, be sure to check that tutorial post.

**Comment by hirasso** [comment]
@yoren thank you for the hint! It now works, after I changed the base tag. Just note, that you should use `home_url()` instead of `site_url()`, since the latter doesn't work if wordpress is installed in a sub-directory.

**Comment by yoren** [comment]
@rassoh Thanks for the info. Just updated the code accordingly.
