### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by t0t** [yoren/angularjs-demo-theme#2]
Hello,

I'm learning with your angularjs-demo-theme a lot.
I saw you dont use the angular directive `ng-controller=""` in order to show the controller's data. 
Please, could you explain why?
thanks!

**Comment by yoren** [comment]
Hey, I didn't do it on purpose, just no need to use it. For now I only use controllers with routers (to manipulate the view).

Please note this project is just for demo, some approaches I took might not be best practices.

**Comment by t0t** [comment]
I know but it is enought for me to learn the basics! ;)
