### ISSUE TITLE
move wp_footer() out of the ng-app view

### ISSUE THREAD

**Issue by hirasso** [yoren/angularjs-demo-theme#3]
Hey! just noticed that the admin bar links were still being caught by angular. moving `wp_footer()` out of the `<div id="page">` fixes this.

**Comment by yoren** [comment]
Hey thank you for reminding this. Not sure why but it seemed work when I wrote that tutorial, but suddenly it didn't work. Moving the wp_footer() did make the WP admin bar work again. Thanks!
