### ISSUE TITLE
multiple pages support

### ISSUE THREAD

**Issue by aryeharmon** [yoren/angularjs-demo-theme#4]
multiple pages support.
menu support so we don't need to refresh the page at all.

Is this a planned extension of this project?

**Comment by yoren** [comment]
Hey there, this project is just for educational purpose. It shouldn't be used on production sites so the features out of the scope of [my tutorials](https://1fix.io/angularjs-wp-rest-api/) won't be added to the theme.

Though I did plan to add pages or menus, just they are not in very high priorities.

Thanks for your suggestion.
